<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{967e055d-0eb5-42dc-b18d-7f8d4f634f3d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	AmrModule					: AmrModule('AMR Module');
	GetSystemTreeJsonHmiVisitor : GetSystemTreeJsonHmiVisitor<1000>('MAIN');
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF NOT AmrModule.Initialized THEN
	AmrModule.Initialize();
	GetSystemTreeJsonHmiVisitor.GetTree(AmrModule);
	RETURN;
END_IF

AmrModule.CyclicLogic();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>